In [1]:
ls

20151201.txt
20151208.txt
capture20110815-3.binetflow
classification_CV.ipynb
classification.ipynb
CSV_CICIDS/
CV_CICIDS.ipynb
CV_CTU.ipynb
CV.ipynb
CV_NSL.ipynb
Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
FridayCICIDS.csv*
Friday-WorkingHours-Morning.pcap_ISCX.csv*
KDD_Classification.ipynb
kddcup_corrected.csv
kddcup.data.corrected.csv
KDDTrain+.csv
NUSW-NB15_features.csv
RNN.ipynb
UNSW-NB15.csv
UNSW_NB15_testing-set.csv
UNSW_NB15_training-set.csv
UNSW_NB15_training-set_selected.csv
Untitled1.ipynb
Untitled.ipynb
Wednesday-workingHours.pcap_ISCX.csv*


In [2]:
import pandas as pd
import numpy as np
import sklearn.metrics as sm
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from collections import Counter
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder,StandardScaler
from mpl_toolkits.mplot3d import Axes3D
from sklearn import metrics
from sklearn.model_selection import train_test_split
import time

In [3]:
def train_split(data,txval,txtest):
    X_train=data.drop(['attack_cat'], axis=1)
    y_train=data['attack_cat']
    X_train1, X_test, Y_train1, Y_test = train_test_split(X_train, y_train, test_size=txtest)
    X_train, X_val, Y_train, Y_val = train_test_split(X_train1, Y_train1, test_size=txval)
    return X_train,Y_train, X_val, Y_val, Y_train, Y_test

data_train = pd.read_csv('./UNSW_NB15_training-set_selected.csv').drop([ 'id', 'label'], axis=1)

X_train,Y_train, X_val, Y_val, X_test, Y_test = train_split(data_train,0.2,0.1)

#print(Counter(Y))

#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

print(Counter(Y_train))
print(Counter(Y_val))
print(Counter(Y_test))

Counter({'Normal': 26647, 'Generic': 13580, 'Exploits': 8022, 'Fuzzers': 4315, 'DoS': 2936, 'Reconnaissance': 2570, 'Analysis': 489, 'Backdoor': 412, 'Shellcode': 275, 'Worms': 32})
Counter({'Normal': 6659, 'Generic': 3365, 'Exploits': 2018, 'Fuzzers': 1107, 'DoS': 773, 'Reconnaissance': 600, 'Analysis': 120, 'Backdoor': 110, 'Shellcode': 60, 'Worms': 8})
Counter({'Normal': 3694, 'Generic': 1926, 'Exploits': 1092, 'Fuzzers': 640, 'DoS': 380, 'Reconnaissance': 326, 'Analysis': 68, 'Backdoor': 61, 'Shellcode': 43, 'Worms': 4})


In [7]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)
print(X)  
KFold(n_splits=2, random_state=None, shuffle=False)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)
    print(y_train)
    print(X_test)
    print(y_test)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]]
[3 4]
[[1 2]
 [3 4]]
[1 2]
TRAIN: [0 1] TEST: [2 3]
[[1 2]
 [3 4]]
[1 2]
[[5 6]
 [7 8]]
[3 4]


In [15]:
100.0 ** -np.arange(1, 10)

array([1.e-03, 1.e-06, 1.e-09, 1.e-12, 1.e-15, 1.e-18, 1.e-21, 1.e-24,
       1.e-27])

In [6]:
data_train.describe()

dur         spkts         dpkts        sbytes        dbytes  \
count  82332.000000  82332.000000  82332.000000  8.233200e+04  8.233200e+04   
mean       1.006756     18.666472     17.545936  7.993908e+03  1.323379e+04   
std        4.710444    133.916353    115.574086  1.716423e+05  1.514715e+05   
min        0.000000      1.000000      0.000000  2.400000e+01  0.000000e+00   
25%        0.000008      2.000000      0.000000  1.140000e+02  0.000000e+00   
50%        0.014138      6.000000      2.000000  5.340000e+02  1.780000e+02   
75%        0.719360     12.000000     10.000000  1.280000e+03  9.560000e+02   
max       59.999989  10646.000000  11018.000000  1.435577e+07  1.465753e+07   

               rate          sttl          dttl         sload         dload  \
count  8.233200e+04  82332.000000  82332.000000  8.233200e+04  8.233200e+04   
mean   8.241089e+04    180.967667     95.713003  6.454902e+07  6.305470e+05   
std    1.486204e+05    101.513358    116.667722  1.798618e+08  2.393001e+06   
min    0.000000e+00      0.000000      0.000000  0.000000e+00  0.000000e+00   
25%    2.860611e+01     62.000000      0.000000  1.120247e+04  0.000000e+00   
50%    2.650177e+03    254.000000     29.000000  5.770032e+05  2.112951e+03   
75%    1.111111e+05    254.000000    252.000000  6.514286e+07  1.585808e+04   
max    1.000000e+06    255.000000    253.000000  5.268000e+09  2.082111e+07   

       ...    ct_dst_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
count  ...  82332.000000      82332.000000      82332.000000    82332.000000   
mean   ...      5.744923          4.928898          3.663011        7.456360   
std    ...      8.418112          8.389545          5.915386       11.415191   
min    ...      1.000000          1.000000          1.000000        1.000000   
25%    ...      1.000000          1.000000          1.000000        1.000000   
50%    ...      2.000000          1.000000          1.000000        3.000000   
75%    ...      6.000000          4.000000          3.000000        6.000000   
max    ...     59.000000         59.000000         38.000000       63.000000   

       is_ftp_login    ct_ftp_cmd  ct_flw_http_mthd    ct_src_ltm  \
count  82332.000000  82332.000000      82332.000000  82332.000000   
mean       0.008284      0.008381          0.129743      6.468360   
std        0.091171      0.092485          0.638683      8.543927   
min        0.000000      0.000000          0.000000      1.000000   
25%        0.000000      0.000000          0.000000      1.000000   
50%        0.000000      0.000000          0.000000      3.000000   
75%        0.000000      0.000000          0.000000      7.000000   
max        2.000000      2.000000         16.000000     60.000000   

         ct_srv_dst  is_sm_ips_ports  
count  82332.000000     82332.000000  
mean       9.164262         0.011126  
std       11.121413         0.104891  
min        1.000000         0.000000  
25%        2.000000         0.000000  
50%        5.000000         0.000000  
75%       11.000000         0.000000  
max       62.000000         1.000000  

[8 rows x 39 columns]