In [1]:
ls

classification.ipynb       NUSW-NB15_features.csv
kddcup_corrected.csv       UNSW-NB15.csv
kddcup.data.corrected.csv  UNSW_NB15_testing-set.csv
KDDTrain+.csv              UNSW_NB15_training-set.csv
kmeans.ipynb               UNSW_NB15_training-set_selected.csv


In [2]:
import pandas as pd
import numpy as np
import sklearn.metrics as sm
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from collections import Counter
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder,StandardScaler
from mpl_toolkits.mplot3d import Axes3D
from sklearn import metrics
from sklearn.model_selection import train_test_split
import time

In [3]:
def train_split(data):
    X_train=data.drop(['attack_cat'], axis=1)
    y_train=data['attack_cat']
    return X_train,y_train

data_train = pd.read_csv('./UNSW_NB15_training-set_selected.csv').drop([ 'id', 'label'], axis=1)

X_train,Y_train = train_split(data_train)

#print(Counter(Y))

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

print(Counter(Y_train))

Counter({'Normal': 37000, 'Generic': 18871, 'Exploits': 11132, 'Fuzzers': 6062, 'DoS': 4089, 'Reconnaissance': 3496, 'Analysis': 677, 'Backdoor': 583, 'Shellcode': 378, 'Worms': 44})
Counter({'Normal': 56000, 'Generic': 40000, 'Exploits': 33393, 'Fuzzers': 18184, 'DoS': 12264, 'Reconnaissance': 10491, 'Analysis': 2000, 'Backdoor': 1746, 'Shellcode': 1133, 'Worms': 130})


In [7]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)
print(X)  
KFold(n_splits=2, random_state=None, shuffle=False)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)
    print(y_train)
    print(X_test)
    print(y_test)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]]
[3 4]
[[1 2]
 [3 4]]
[1 2]
TRAIN: [0 1] TEST: [2 3]
[[1 2]
 [3 4]]
[1 2]
[[5 6]
 [7 8]]
[3 4]
